### ISSUE TITLE
Integrate this into netdata.

### ISSUE THREAD

**Issue by simonnagl** [simonnagl/netdata-plugin-java-daemon#41]
Author: @ktsaou
> Integrating this into netdata would also be nice. I guess this would require some more work to build it using the netdata automake system and install it with the rest.

What do you mean with integrating?
Putting it completely into the [netdata project](https://github.com/firehol/netdata)? When I started implementing this I decided to do it in a separate project mainly because java has a much different build system. My thoughts where these: Netdata could add this to the installer. The installer will decide if java is there. If yes it downloads this plugin and runs the plugins installer. If no we do not need this plugin. We won't be able to compile it anyways.

**Comment by ktsaou** [comment]
Well, my initial thoughts was that automake can handle this.

So, we can move everything to the netdata repo in a directory and have automake decide if java is there or not. If it is there, it should build it.

I have done something similar with the `freeipmi` plugin. Automake by default detects if freeipmi is available and enables or disables the plugin. But the user can give command line options (to configure and netdata-installer.sh) to overwrite this decision (i.e. disable it, or required it).

If it was built, `make install` also installs it.

Given that netdata ships many versions of the files (git source, .tar version, binary versions, etc) the best is to have it inside the repo. Then all versions will be shipped it too.

Also, the distros will really get confused if automake starts downloading more files. In most of the cases they also ship source packages and this automatic downloading technique will most probably raise issues.

**Comment by simonnagl** [comment]
> So, we can move everything to the netdata repo in a directory and have automake decide if java is there or not. If it is there, it should build it.

I think this could work. Adding the maven wrapper to the root directory of the plugin and letting automake execute it should work. The automated tests then should also run in travis if we add the java dependencies.

I think I will continue developing here until I would release a 1.0.0. Then I will not release this version but integrate it to netdata.

Currently this project is not stable enough to make it into the beatiful netdata project.

@ktsaou Thank you for contributing here. Your knowledge really helps.

**Comment by simonnagl** [comment]
I am closing this during issue migration to `netdata`. If you want to contribute to this thread please do at the migration pull request https://github.com/firehol/netdata/pull/2663
