### ISSUE TITLE
Discussion: Which configuration language to use.

### ISSUE THREAD

**Issue by simonnagl** [simonnagl/netdata-plugin-java-daemon#42]
@ktsaou started a discussion about configuration languages in #39. Let's continue it here.

Currently we use json. Me may switch this.

Arguments of @ktsaou:
* standard practice for java apps config files is `xml`.
* `json` does not support comments so extensive documentation is needed in separate files.
* For node.js plugins I would definitely use `yaml` if there was a javascript-only implementation `yaml` library.

My Arguments:
* XML is not very readable.
* We extend JSON to support Java/C-like comments in this project
* Jackson (the parser library we use) has a `yaml` extension. I never used it but we could try.

**Comment by simonnagl** [comment]
I interpret the thumbs up of @ktsaou that he accepts my decision to use `json` extended with comments for configuring the java plugin.

**Comment by ktsaou** [comment]
If it is the same for you, I would give `yaml` a try.
Your call...
