### ISSUE TITLE
Plans to implement jvm process heap monitoring?

### ISSUE THREAD

**Issue by S4NT14G0** [simonnagl/netdata-plugin-java-daemon#48]
Is there a way to monitor jvm process heap with this plugin?  If not this feature could be very useful.  Great plugin btw!

**Comment by simonnagl** [comment]
Thank you. This ist not possible from this repository. There is a MR (https://github.com/firehol/netdata/pull/2663) to add this plugin to the `netdata` repository. The MR is able to monitor jvm heap sizes. If you need further information please ask.
